settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: liao-world-chat
    name: liao.world
    url: 'https://status-api-worker.410915218.workers.dev/?address=liao.world'
    method: GET
    linkable: false
    expectStatus: 200

  - id: liaobots-3-5
    name: liaobots-3.5
    linkable: false
    url: 'https://status-api-worker.410915218.workers.dev/?address=liaobots-3.5'
    method: GET
    expectStatus: 200

  - id: liaobots-4
    name: liaobots-4
    linkable: false
    url: 'https://status-api-worker.410915218.workers.dev/?address=liaobots-4'
    method: GET
    expectStatus: 200
